server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.instance}
    username: ${db.username}
    password: ${db.password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  profiles:
#    active: @activeProfile@
#
##Настройка логирования из pom.xml
#logging:
#  config: classpath:@loggingConfigFile@