server:
  port: 8081

external:
  api:
    get:
      currensy-rate:
        url: https://www.cbr-xml-daily.ru/daily_json.js

inside:
  api:
    post:
      currensy-rate:
#  TODO: for docker
#        url: http://main-service:8080/currency-rate
        url: http://127.0.0.1:8080/currency-rate